function [BW,maskedImage] = modActiveContour(im, mask)
%segmentImage segments image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = modActiveCountour(IM) segments image IM using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW and a masked image is returned in MASKEDIMAGE.
% 
%  Added with Otsu segmentation for improved masking.

% Auto-generated by imageSegmenter app on 21-Oct-2015
%----------------------------------------------------


% Initialize segmentation with threshold
%mask = im>5;
%im = double(im) ./ max(double(im(:)));
%im = shadingCorrection(im);
if nargin < 2
    mask = binaryFromLevels(im,multithresh(im,2));
end

% Evolve segmentation
BW = activecontour(im, mask, 200, 'edge'); % ... or Chan-Vese

% Fill holes
BW = imfill(BW, 'holes');

regS = regionprops(BW);
           
M = mean([regS.Area]);
S = std([regS.Area]);

minblob = max(210,(M-3*S)/4);
% Filter components by area
BW = bwareafilt(BW, [minblob Inf]); % minblob

% Form masked image from input image and segmented image.
maskedImage = im;
maskedImage(~BW) = 0;
end
