function [BW,maskedImage] = simpleAdaptiveSegmentation(X)
% simpleAdaptiveSegmentation Segment image using auto-generated code from imageSegmenter App
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter App. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.
% 


% Auto-generated by imageSegmenter app on 06-Feb-2017
%----------------------------------------------------

if size(X,3) == 3
    X = X(:,:,2);
end

% Threshold image - adaptive threshold
BW = imbinarize(X, 'adaptive', 'Sensitivity', 0.230000,...
    'ForegroundPolarity', 'bright');

% Clear borders
BW = imclearborder(BW);

% Erode mask with disk
radius = 1;
decomposition = 0;
se = strel('disk', radius, decomposition);
BW = imerode(BW, se);
BW = bwmorph(BW, 'clean');

% Create masked image.
if nargout > 1
    maskedImage = X;
    maskedImage(~BW) = 0;
end